---
kind: pipeline
type: docker
name: backend

steps:
- name: run tests
  image: python:3.11
  environment:
    PYTHONPATH: /drone/src/src
  commands:
  - pip install poetry
  - poetry install
  - poetry run pytest

trigger:
  event:
    exclude:
    - pull_request
